version: '3.1'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
  
  app:
    image: cacolorde/daggerize-node
    environment:
      - DB_SERVER=sql-server
      - DB_USER=sa
      - DB_PASSWORD=Password123
    ports:
      - "3000:3000"
    depends_on:
      - sql-server