name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ts-node
        run: npm install ts-node
      - name: Dagger
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: node --loader ts-node/esm ./test.mts
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_HUB_USERNAME: cacolorde
