name: Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dagger
        uses: dagger/dagger-for-github@v5
        with:
          verb: dagger run
          args: node --loader ts-node/esm ./test.mts
